title: Anna White
description: >
  Ann White is a PhD student in Industrial and Operations Engineering,
  University of Michigan, Ann Arbor.
copyright: Anna White
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "anna-white-80a169128"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "#"
gscholar: https://scholar.google.co.nz/citations?hl=en&view_op=list_works&gmla=AJsN-F7ua45BO8i1DHccKCUj7VPZqMzoZxfTFasDQNl2_V7GtlfsDKuC70DN5-8fIn8VadBbpoEfmI9BTw5FwKbSHXWa_N0IKA&user=NqnK14EAAAAJ
# feed_icon: rss
email: "agracew@umich.edu"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
