title: Anna White
description: >
  Anna White is a PhD student in Industrial and Operations Engineering,
  University of Michigan, Ann Arbor.
copyright: Anna White
sass:
  sass_dir: assets/sass
url: ''
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username:
linkedin_username: "anna-white-80a169128"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "agracew"
scholar_username: 
# feed_icon: rss
email: "agracew@umich.edu"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
